version: '3.8'
services:
  localstack:
    image: localstack/localstack:4.12
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "4510:4510"
      - "9200:9200"
      - "4510-4559:4510-4559"
      - "8080:8080"
    environment:
      - SERVICES=lambda,s3,events,opensearch,ses,transcribe
      - DEBUG=1
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY:-}
      - OPENSEARCH_ENDPOINT_STRATEGY=port
      - OPENSEARCH_PORT_EXTERNAL=4571
      - OPENSEARCH_PORT=9200
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack_data:/var/lib/localstack"
      - "./lambda_functions:/var/lib/localstack/lambda_functions"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - localstack-network

networks:
  localstack-network:
    driver: bridge


# aws --endpoint-url=http://localhost:4566 opensearch create-domain   --domain-name test-domain
# --engine-version OpenSearch_2.5   --cluster-config '{"InstanceType":"m3.medium.search","InstanceCount":1}'
# --ebs-options '{"EBSEnabled":true,"VolumeType":"gp2","VolumeSize":10}'
